# -*- coding: utf-8 -*-
"""ForestFire.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cW645hGcCFu1Y_9KPx1Ypuy5K21tVB35
"""

import csv
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df_tracks = pd.read_csv('/content/drive/MyDrive/fire_archive_M6_96619.csv')
df_tracks

dataMapping={
    'D':1,
    'N':0
}
df_tracks['Daynight']=df_tracks['daynight'].map(dataMapping)
df_tracks=df_tracks.drop(['acq_date','acq_time','satellite','instrument','version','daynight','type'],axis=1)

df_tracks

df_tracks=df_tracks.loc[:,['latitude','longitude','brightness','scan','track','bright_t31','frp','Daynight','confidence']]
df_tracks

attributes=['latitude','longitude','brightness','scan','track','bright_t31','frp','Daynight']
x=df_tracks[attributes]
y=df_tracks['confidence']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

Model= RandomForestRegressor(n_estimators=300, random_state = 42, n_jobs = -1)
Model.fit(X_train, y_train)
y_pred = Model.predict(X_test)
y_pred=np.array(y_pred)

y_pred=y_pred.reshape(-1,1)
y_pred

Confidence = y_pred
file_n = 'Sample_Submission.csv'
with open(file_n, 'w', newline='') as csvfile:
    csv_w = csv.writer(csvfile)
    for confidence in Confidence:
        csv_w.writerow([confidence])

random_model_accuracy1 = round(Model.score(X_test, y_test)*100,2)
print(round(random_model_accuracy1, 2), '%')